
apiVersion: metallb.io/v1beta1
kind: IPAddressPool
metadata:
  name: sandbox
  namespace: metallb-system
spec:
  addresses:
  - 172.16.109.166-172.16.109.168
---
apiVersion: metallb.io/v1beta1
kind: L2Advertisement
metadata:
  name: sandbox
  namespace: metallb-system
spec:
  ipAddressPools:
    - sandbox
